spring.application.name=ScaleApplication
server.port=8081

# TO?G?RI ? faqat scaledb ga ulanish
spring.datasource.url=jdbc:postgresql://localhost:5432/scaledb
spring.datasource.username=postgres
spring.datasource.password=olimjon00
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Fayl yuklash
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# Qolgan sozlamalar
number.pattern.regexp.number=^(01|10|20|25|30|40|50|60|70|75|80|85|90|95)(\\d{3}[A-Z]{3}|[A-Z]{1}\\d{3}[A-Z]{2})$
number.pattern.regexp.standard=^(?=(?:.*[A-Z]){5,})(?:[A-Z0-9-]*)[0-9]{0,2}(?:[A-Z-]*)$
spring.url=https://api.uzkimyo.uz/be/api/v1
spring.username=n_tarozibon
spring.password=1